config/routes.rb
RadishApp::Application.routes.draw do
  get "signin/index"

  get "home/index"

  get "blog/index"

  match 'signin' => 'signin#index'
  match 'blog' => 'blog#index'

    root :to => 'home#index'

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  render :layout => 'about'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  render :layout => 'contact'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/signin_controller.rb
class SigninController < ApplicationController
  def index
  render :layout => 'signin'
  end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/signin_helper.rb
module SigninHelper
end

app/views/about/index.html.erb
<% content_for :head do %>
    <title>About Controller</title>
<%end %>

<% content_for :heading do %>
    <h1>Welcome to the About Page</h1>
<%end %>

<h1>About Us</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/blog/index.html.erb
<div class="pg-wrap">
    <h1>Radish Blog</h1>
    <p>Find me in app/views/blog/index.html.erb</p>



<ul class="blog"> 
        <% 6.times do %>
        <li>
        <h3>BLOG POST</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        </li>
        <% end %>
</ul>

</div>

app/views/contact/index.html.erb
<% content_for :head do %>
    <title>content Controller</title>
<%end %>

<% content_for :heading do %>
    <h1>Welcome to the Contact Page</h1>
<%end %>

<h1>Contact Us</h1>
<p>Find me in app/VIEWS/about/index.html.erb</p>

<%= render 'shared/sidebar'%>

app/views/home/index.html.erb
<section id="container">
    <section id="browser-preview">
        <div class="wrapper">
            <%= image_tag("browser.png", :class => 'browser-image') %>
        </div> <!-- /wrapper -->
    </section>

    <div id="marketing-wrapper">
        <div id="content-wrapper">
            <section id="features">
                    <h2>Dig Deep Into Redis</h2>
                    
                    <div class="column left">
                        <div class="thumb" id="metrics"></div>
                        <h4>SMART METRICS</h4>
                        <p>Tracking project specific metrics is made easy with Radish. Sparklines quickly show high density data in a simplified and useful manner.</p>
                    </div>
                
                    <div class="column">
                        <div class="thumb" id="interface"></div>
                        <h4>INTELLIGENT INTERFACE</h4>
                        <p>Radish is equipped with a minimal user interface that stands out of the way, empowering you to focus on data and project metrics.</p>
                    </div>
                
                    <div class="column right">
                        <div class="thumb" id="monitor"></div>
                        <h4>REAL-TIME MONITORING</h4>
                        <p>Monitor critical incoming data for bottlenecks and spikes. Radish enables you to visualize your redis instances so you can take action when necessary.</p>
                    </div>
            </section>
    <hr>
        <section id="sign-up">
            <div id="free-trial">
                <h3>SIGN UP FOR A FREE TRIAL</h3>
                
                <%= render 'shared/sign-up-form'%>
            
            </div>
        </section>    
        </div>
    </div>
</section>

app/views/layouts/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="pg-wrap">

<header>
<%= render 'shared/nav'%>
</header>

    <div id="content">
        <%= yield %>
    </div> <!-- /content -->

<div id="sidebar">
<%= render 'shared/sidebar'%>
</div>

</div> <!-- /pg-wrap -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RadishApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'shared/header'%>

<%= yield %>

<%= render 'shared/footer'%>

</body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= yield :head %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="pg-wrap">

<header>
<%= render 'shared/nav'%>
</header>

    <div id="content">
        <%= yield %>
    </div> <!-- /content -->

<div id="sidebar">
<%= render 'shared/sidebar'%>
</div>

</div> <!-- /pg-wrap -->

</body>
</html>

app/views/layouts/signin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RadishApp</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_footer.html.erb
<footer>
    <hr>
    <div class="wrapper">
        <ul id="navigation">
            <li><%= link_to "Sign In", signin_path %></li>
            <li><%= link_to "Plans & Pricing", root_path %></li>
            <li><%= link_to "SUPPORT", root_path %></li>
            <li><%= link_to "TERMS OF SERVICE", root_path %></li>
            <li><%= link_to "PRIVACY", root_path %></li>
            <li><%= link_to "CONTACT", root_path %></li>
            <li><%= link_to "TWITTER", root_path %></li>
            <li><%= link_to "HELP", root_path %></li>     
        </ul>
          
        <p>The name and logo of Radish are registered trademarks of thoughtbot, inc.<br/> 
        All text and design is copyright 2011 thoughtbot, inc. All rights reserved.</p>
    </div>

    <div id="thoughtbot-logo"> 
        <%= image_tag("thoughtbot-logo.png", :class => '') %>
    </div>   
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="wrapper">
        <%= link_to root_path, :id => "radish-logo" do %>
            <h1>Radish</h1>
        <% end %>
        
        <nav>
            <%= link_to "BLOG  |  ", blog_path %>

            <%= link_to "sign in", signin_path %>
            <%= link_to "sign up", root_path, :class => 'sign-up' %>
        </nav>
    </div> <!-- /wrapper -->
</header>

app/views/shared/_nav.html.erb
<nav>
    <%= link_to "Home", root_path %>
    <%= link_to "About", about_path %>
    <%= link_to "Contact", contact_path %>
</nav>

app/views/shared/_sidebar.html.erb
<h2>sidebar title</h2>
<ul>
    <li>list item </li>
    <li>list item</li>
    <li>list item</li>
</ul>

app/views/shared/_sign-up-form.html.erb
<form id="simple-signup" method="post" action="#">
    <input id="email" name="signup[email]" type="email" placeholder="Your Email">
    <input id="password" name="signup[password]" type="password" placeholder="Password">
    <p>Sorry, we're currently not accepting new sign ups.</p>
</form> 

app/views/signin/index.html.erb
<header class="sign-in">
    
    <%= link_to root_path do %>
        <h1>Radish</h1>
    <% end %>
    
    
</header>


<section class="sign-in-form">
    <h1>Signin Here</h1>
    <%= render 'shared/sign-up-form'%>
</section>